name = "NlmeData"
uuid = "fdf73e9b-dfac-4a1a-bc04-5d360d62932c"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
Arrow = "1"
julia = "1.6, 1.7, 1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
