name = "nlmedata"
uuid = "fdf73e9b-dfac-4a1a-bc04-5d360d62932c"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Arrow = "1"
Artifacts = "1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
